### ISSUE TITLE
Setup GHA, automatic release from mn2pdf.JAR

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf-ruby#1]
We need to setup GHA for this repo:

1. `rake spec`
2. We need to link release of mn2pdf.JAR to set the same version number of this gem, and release the gem

**Comment by ronaldtse** [comment]
Newly added `rake bin/mn2pdf.jar` will pull correct version of mn2pdf.jar. So in build, run:

```
rm -f bin/mn2pdf.jar
rake bin/mn2pdf.jar
rake release
```

**Comment by CAMOBAP** [comment]
@ronaldtse let me know once `RUBYGEMS_API_KEY` ready and I will do release

**Comment by ronaldtse** [comment]
`RUBYGEMS_API_KEY` is now ready.

**Comment by CAMOBAP** [comment]
Done, 1.13 already released but the logic works
