### ISSUE TITLE
Catch errors coming out of PDF Java

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn2pdf-ruby#10]
Just now I've checked on Ubuntu (on Windows bundle update doesn't working) and PDF generated ok.
But looks like when ruby call java mn2pdf application it doesn't redirect message to console, so there aren't any messages for mn2pdf.
I'm not ruby spec at all, but may be need to add an instruction:
{SDTERR=>STDOUT}
See:
https://stackoverflow.com/questions/29829204/how-to-pass-parameters-to-a-jar-file-and-read-the-console-output-in-ruby
https://stackoverflow.com/questions/10354602/how-to-get-java-output-with-ruby?nah=29826744#29826744

**Comment by opoudjis** [comment]
@Intelligent2013 passed this ticket on to @w00lf

**Comment by w00lf** [comment]
@opoudjis as it turns out, mn2pdf writes errors into STDOUT instead of STDERR:
![image](https://user-images.githubusercontent.com/1158036/96363792-0afe9380-113f-11eb-99e1-aee21a4b4f75.png)

I have changed the library to actually display messages from STDOUT:

![image](https://user-images.githubusercontent.com/1158036/96363808-27023500-113f-11eb-83aa-71a20daac027.png)

**Comment by ronaldtse** [comment]
@w00lf we clearly prefer error messages going to STDERR from mn2pdf. Ping @Intelligent2013

**Comment by Intelligent2013** [comment]
@w00lf We need to catch all messages - from STDOUT and STDERR. Apache FOP puts the message into both.

**Comment by w00lf** [comment]
> @w00lf We need to catch all messages - from STDOUT and STDERR. Apache FOP puts the message into both.

I have created PR for this: #11

**Comment by opoudjis** [comment]
Thank you!

**Comment by Intelligent2013** [comment]
Source issue: https://github.com/metanorma/mn-samples-itu/issues/152#issue-1378703596.

Again, there aren't any messages for mn2pdf on the console. The messages after `java -Xss5m -Xmx2048m -jar /github/home/.local/share/gem/ruby/3.0.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar ` relates to the next actions, not mn2pdf.

From https://github.com/metanorma/mn-samples-itu/actions/runs/3086698559/jobs/4991315641:
```
Metanorma XML Syntax: (XML Line 003151:18): element "docidentifier" not allowed yet; missing required element "title"
java -Xss5m -Xmx2048m -jar /github/home/.local/share/gem/ruby/3.0.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/__w/mn-samples-itu/mn-samples-itu/site/documents/G.191.presentation.xml" --xsl-file "/github/home/.local/share/gem/ruby/3.0.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/itu.recommendation.xsl" --pdf-file "/__w/mn-samples-itu/mn-samples-itu/site/documents/G.191.pdf" --param baseassetpath="/__w/mn-samples-itu/mn-samples-itu/sources" --syntax-highlight  --font-manifest "/tmp/fontist_locations20220920-2181-878m0h.yml"
[info]: Compiling /__w/mn-samples-itu/mn-samples-itu/sources/G.650.1-201803.adoc ...
[relaton-itu] ("ITU-T G.650.2") fetching...
```

**Comment by CAMOBAP** [comment]
Already resolved in https://github.com/metanorma/mn-samples-itu/pull/153
