### ISSUE TITLE
Macos Java icon jumping in dockbar

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn2pdf-ruby#15]
### Problem

Affects only macOS users AFAIK. Once metanorma call java icon appears in the dock like this:

<img width="308" alt="Screen Shot 2021-02-22 at 2 48 24 PM" src="https://user-images.githubusercontent.com/2169738/108704710-71485800-751d-11eb-89a0-592edde96ce8.png">

it's really annoying and distracting (especially if there are several separate java calls) because:
 - it shows the dock if it was closed previously
 - it switches you to the first virtual screen if you are working with multiple virtual screens

### Solution

Pass `-Dapple.awt.UIElement=true` to java cmd

https://stackoverflow.com/questions/17460777/stop-java-coffee-cup-icon-from-appearing-in-the-dock-on-mac-osx

P.S. @ronaldtse IDK how this annoying for other users (except me), let me know if you have some information/feedback

**Comment by ronaldtse** [comment]
It certainly annoys me... Did not know it was possible to disable it. Thanks for the solution! 👍

**Comment by ronaldtse** [comment]
In this case please also help fix mn2sts-ruby because it has the same issue too.

**Comment by CAMOBAP** [comment]
PRs ready for review

**Comment by ronaldtse** [comment]
All merged, feel free to close if it's done @CAMOBAP !
