### ISSUE TITLE
mn2pdf.jar is over 50M

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn2pdf-ruby#29]
@ronaldtse @Intelligent2013 mn2pdf.jar is over 50M right now, should we consider moving it to LFS? To avoid the repo "exploding" issue?

more about git lfs https://git-lfs.github.com/

**Comment by ronaldtse** [comment]
@CAMOBAP yes let's use LFS for it. Thanks!

**Comment by ronaldtse** [comment]
Enabled.

**Comment by ronaldtse** [comment]
Actually, can we just remove the JAR from the Git repo, and dynamically fetch it from the mn2pdf release during the build process?

**Comment by CAMOBAP** [comment]
I think yes, we just need to update `mn2pdf.gemspec` because it rely on files tracked by `git`
