### ISSUE TITLE
Auto-release of gem not working

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf-ruby#31]
https://github.com/metanorma/mn2pdf-ruby/runs/6434982544?check_suite_focus=true#step:7:1

Seems that the release-tag workflow doesn't work, which is blocking auto-release of the mn2pdf gem.
<img width="1427" alt="Screenshot 2022-05-20 at 12 29 24 AM" src="https://user-images.githubusercontent.com/11865/169351170-16fd9b1c-1de5-4a99-8650-ff76e57762df.png">

**Comment by CAMOBAP** [comment]
Fixed, to give you a full picture, once we do some work on mn2pdf-ruby and need to release we temporally "unbind" the version from mn2pdf and mn2pdf-ruby. This is why release failed

Worst problem that by default there is no way to get notification once some cron or repository_dispatch job failed

https://github.com/dawidd6/action-send-mail can help us here

@ronaldtse I propose to add send-email step to our workflow as workaround. I will configure critical repos like `chocolatey` `snap`, `homebrew` and this one, to react ASAP

From your side, may I ask you to configure org-level secrets:
 - secrets.MAIL_USERNAME
 - secrets.MAIL_PASSWORD

Also if we need to hide or SMPT server port we can add this to secrets too

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
This is now resolved -- we created an email forwarder that sends metanorma-ci build notifications to @CAMOBAP and @opoudjis .
