### ISSUE TITLE
Allow configuration of mn2pdf stack and heap space 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf-ruby#39]
From:
* https://github.com/metanorma/metanorma-cli/issues/326
* https://github.com/metanorma/iso-2533/issues/20

The change starts here:
https://github.com/metanorma/mn2pdf-ruby/blob/7c981c12fac46b25c62845a965862433fd577391/lib/mn2pdf.rb#L8

We need to be able to change the JVM memory options:
* `Xss` stack size, defaults to `1m`, we use `5m`
* `Xms` heap initial size
* `Xmx` heap max size, defaults to half of physical memory up to `192m`. We default to `2g`. However for metanorma/iso-2533#20 a size of `6g` was needed

So we need a way to configure these through library method invocation. These parameters are directly used by:
* https://github.com/metanorma/metanorma-cli/issues/326

**Comment by CAMOBAP** [comment]
I think it should read JAVA opts from env (`JAVA_OPTS`) and ensure that `ss` and `mx` are at least `5m` and `2048m`. this will allow to change it and give final client flexibility also for huge docs

An alternative approach for passing through metanorma-cli looks complex and redundant and make sense only for our code and not external tools

**Comment by CAMOBAP** [comment]
Implemented via JAVA_OPTS env var
