### ISSUE TITLE
Fix release-tag GHA job

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf-ruby#4]
There was something wrong with the GHA syntax. @CAMOBAP can you help fix it? Thanks.

https://github.com/metanorma/mn2pdf-ruby/actions/runs/96013799

**Comment by CAMOBAP** [comment]
Already fixed by https://github.com/metanorma/mn2pdf-ruby/commit/bcc16346b0681d567e8a412cd6f105d18da8948f
