### ISSUE TITLE
mn2pdf-ruby auto-tag failed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf-ruby#5]
https://github.com/metanorma/mn2pdf-ruby/runs/659520336?check_suite_focus=true

**Comment by CAMOBAP** [comment]
Issues on release.yml & release-tag.yml fixed but here is a problem with trigger release.yml after release-tag.yml still investigating the problem...

**Comment by CAMOBAP** [comment]
Fixed https://github.community/t5/GitHub-Actions/Action-does-not-trigger-another-on-push-tag-action/m-p/41035#M4466
