### ISSUE TITLE
(URGENT) Actually release the gem to Rubygems on release_tag

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf-ruby#7]
The gems are released on this repo, but not actually to Rubygems. The command `bundle exec rake release` should be run at release.

<img width="605" alt="Screen Shot 2020-06-24 at 2 23 10 PM" src="https://user-images.githubusercontent.com/11865/85508229-3c020800-b626-11ea-9a96-9dcfe17cb3d5.png">

<img width="920" alt="Screen Shot 2020-06-24 at 2 23 24 PM" src="https://user-images.githubusercontent.com/11865/85508245-43c1ac80-b626-11ea-8f30-ce14b4fc5959.png">

**Comment by CAMOBAP** [comment]
@ronaldtse could you please confirm that `secrets.METANORMA_CI_PAT_TOKEN` created for this repo?

**Comment by ronaldtse** [comment]
Let me check.

**Comment by ronaldtse** [comment]
Yes, it has been available for this repo.

**Comment by ronaldtse** [comment]
And `METANORMA_CI_RUBYGEMS_API_KEY`.

**Comment by CAMOBAP** [comment]
Done, I did manual release for last 1.18 version, but for the next one it will work automatically

The problem was that `git push` with `x-access-token` doesn't trigger CI, I thought that I fixed this issue in all repos, but unfortunately I have missed this one(

**Comment by CAMOBAP** [comment]
*Now I watch for this repo to make sure that next release will works

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
